// Generated by CoffeeScript 1.6.3
var fs, pipeline, program, realize;

fs = require('fs');

program = require('commander');

pipeline = require('when/pipeline');

module.exports = realize = {
  marshalArgs: function(program) {
    program.version(JSON.parse(fs.readFileSync(__dirname + '/../package.json'), 'utf8').version);
    program.usage('[options] [realizer]');
    program.option('-p, --port  <num>      ', 'Connect to Objective at port');
    program.option('-X, --no-https         ', 'Connect insecurely', false);
    program.parse(process.argv);
    return {
      filename: program.args[0],
      connect: true,
      https: program.https,
      port: program.port
    };
  },
  exitWithError: function(error) {
    process.stderr.write(error.toString());
    return process.exit(error.errno || 100);
  },
  withError: function(errno, code, message) {
    var error;
    error = new Error(message);
    error.errno = errno;
    error.code = code;
    return error;
  },
  exec: function() {
    return pipeline([
      function() {
        return realize.marshalArgs(program);
      }, function(params) {}
    ]).then(function(resolve) {}, realize.exitWithError, function(notify) {});
  }
};
