// Generated by CoffeeScript 1.6.3
var configure, deferred, error;

deferred = require('also').deferred;

error = require('./').error;

module.exports = configure = deferred(function(action, params) {
  return action.resolve('pending realizer');
});
