// Generated by CoffeeScript 1.6.3
var connect, deferred, error;

deferred = require('also').deferred;

error = require('./error');

module.exports = connect = deferred(function(action, realizer) {
  return action.resolve('pending controls');
});
