// Generated by CoffeeScript 1.6.3
var connect, deferred, error;

deferred = require('also').deferred;

error = require('./error');

module.exports = connect = deferred(function(action, realizer) {
  var notify, opts, realizerFn, reject, resolve;
  resolve = action.resolve, reject = action.reject, notify = action.notify;
  opts = realizer.opts, realizerFn = realizer.realizerFn;
  return console.log({
    OPTS: opts
  });
});
