// Generated by CoffeeScript 1.6.3
module.exports = function(_arg) {
  var code, detail, errno, error, message;
  errno = _arg.errno, code = _arg.code, message = _arg.message, detail = _arg.detail;
  error = new Error(message);
  error.errno = errno;
  error.code = code;
  error.detail = detail;
  return error;
};
