// Generated by CoffeeScript 1.6.3
var mod, modules, _i, _len;

modules = ['configure', 'connect', 'run', 'error'];

for (_i = 0, _len = modules.length; _i < _len; _i++) {
  mod = modules[_i];
  module.exports[mod] = require("./" + mod);
}
