// Generated by CoffeeScript 1.6.3
var deferred, error, hostname, phrase, run;

deferred = require('also').deferred;

hostname = require('os').hostname;

phrase = require('phrase');

error = require('./error');

module.exports = run = deferred(function(action, controls) {
  var load, notify, opts, phraseRecursor, readyCount, realizerFn, reject, resolve, uplink,
    _this = this;
  resolve = action.resolve, reject = action.reject, notify = action.notify;
  uplink = controls.uplink, opts = controls.opts, realizerFn = controls.realizerFn;
  opts.notice = uplink;
  readyCount = 0;
  phraseRecursor = phrase.createRoot(opts, function(token) {
    _this.token = token;
  });
  load = function() {
    return phraseRecursor('realizer', realizerFn);
  };
  return uplink.use(function(msg, next) {
    /* realizer middleware 1*/

    var err, key;
    switch (msg.direction) {
      case 'out':
        msg.uuid = opts.uuid;
        msg.pid = process.pid;
        msg.hostname = hostname();
        console.log({
          SENDING: msg.context
        }, msg);
        return next();
      case 'in':
        console.log({
          RECEIVING: msg.context
        }, msg);
        switch (msg.event) {
          case 'reject':
            err = error({
              errno: 107,
              code: 'ENO',
              message: msg.event,
              detail: {}
            });
            for (key in msg) {
              err.detail[key] = msg[key];
            }
            reject(err);
            return next();
          case 'load':
            load().then(function(result) {
              return uplink.event.good("ready::" + (++readyCount));
            }, function(error) {
              var payload;
              payload = {
                error: error.toString()
              };
              try {
                payload.stack = error.stack;
              } catch (_error) {}
              return uplink.event.bad('error', payload);
            });
            return next();
        }
        return next();
    }
  });
});
